import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const manifest = JSON.parse(readFileSync("plugin.json", "utf8"));
const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const makefile = readFileSync("Makefile", "utf8");
assert.equal(manifest.version, pkg.version);
assert.equal(manifest.contributes.views[0].surfaces[0], "side");
assert.equal(manifest.contributes.views[0].id, "process-monitor");
assert.deepEqual(manifest.contributes.commands.map((command) => command.name), ["refresh", "status", "wait"]);
assert.deepEqual(JSON.parse(readFileSync("release-files.json", "utf8")), ["LICENSE", "main.js", "plugin.json"]);
for (const target of ["preflight", "prepare", "build", "verify", "release", "attest", "publish-local", "require-tooling", "require-out", "require-store"]) assert.match(makefile, new RegExp(`^${target}:`, "m"));
assert.match(makefile, /SDK_VERSION := 0\.0\.20/);
assert.match(makefile, /soksak-sdk package/);
assert.match(makefile, /--store "\$\(STORE\)"/);
assert.match(makefile, /^publish-local: attest$/m);
assert.match(makefile, /soksak-local-release publish --store "\$\(STORE\)" --release "\$\(OUT\)"/);
